services:
  djikstra:
    image: tttriplicate/djikstra:simple
    links:
      - mysql
    depends_on:
      - "mysql"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./Database:/docker-entrypoint-initdb.d/